name: Test Coverage

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-coverage:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Get pnpm version
        id: packageManager
        run: echo "version=$(node -p "require('./package.json').packageManager.split('@')[1]")" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
        with:
          version: ${{ steps.packageManager.outputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm type-check

      - name: Lint code
        run: pnpm lint

      - name: Run tests with coverage
        run: pnpm test:coverage
        env:
          CI: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true